apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-app-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: product
  source:
    repoURL: https://github.com/luca-poddigue-hs/kcb-apps.git
    targetRevision: "main"
    path: apps-manifests/product-app-1
    kustomize:
      namePrefix: kustomize-
  destination:
    server: https://kubernetes.default.svc
    namespace: product