apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/luca-poddigue-hs/kcb-apps.git
    targetRevision: "main"
    path: apps/platform/build/c1
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
