apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-applications
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/luca-poddigue-hs/kcb-apps.git
    targetRevision: "main"
    path: apps/product
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
